name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "none@example.org"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bash \
            bzr \
            bc \
            binutils \
            build-essential \
            bzip2 \
            cpio \
            cvs \
            diffutils \
            file \
            findutils \
            g++-multilib \
            gcc-multilib \
            git \
            gzip \
            libclang-dev \
            make \
            mercurial \
            openssh-client \
            patch \
            perl \
            python3 \
            rsync \
            sed \
            subversion \
            tar \
            unzip \
            wget

      - name: Build Image
        run: make image

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: output/images/rootfs.cpio.xz

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: output/images/rootfs.cpio.xz
